pool:
  vmImage: ubuntu-20.04

stages:
- stage: continuous_integration
  displayName: Continuous Integration
  jobs:
  - job: framework
    displayName: Framework
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - script: dotnet --version
      displayName: Check .NET SDK version

  - job: restore
    displayName: Restore NuGet packages
    dependsOn: framework
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - script: dotnet restore

  - job: build
    displayName: Build and Run
    dependsOn: restore
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - script: dotnet framework
      displayName: Framework .NET project
    - script: dotnet run
      displayName: Run .NET application